#include <gtest/gtest.h>

#include <cstdint>
#include <cstring>
#include <fstream>
#include <string>
#include <vector>

#include <campello_llm/gguf_reader.hpp>

using namespace systems::leal::campello_llm;

namespace
{
    std::string fixturePath(const std::string &name)
    {
        return std::string(CAMPELLO_LLM_TEST_FIXTURES_DIR) + "/" + name;
    }
} // namespace

// Fixture generated by tests/fixtures/generate_test_gguf.py (real `gguf` Python
// package's GGUFWriter) — exact expected bytes/shapes verified against the actual
// generated file (via `python3 -m gguf.scripts.gguf_dump`) before being hardcoded
// here. Note gguf's on-disk dim order is reversed from the numpy shape the fixture
// script wrote (ggml lists the fastest-varying dimension first) — `weight`'s numpy
// shape (2, 3) is stored as dims [3, 2], and this reader intentionally reads dims in
// raw file order without un-reversing them (Phase 1 is architecture-agnostic; any
// shape-order convention is the architecture registry's concern, not this reader's).

TEST(GgufReader, ReadsAllTensorsFromFile)
{
    auto file = loadGgufFromFile(fixturePath("test_tensors.gguf"));
    ASSERT_NE(file, nullptr);
    EXPECT_EQ(file->tensors().size(), 3u);
}

TEST(GgufReader, WeightTensorF32)
{
    auto file = loadGgufFromFile(fixturePath("test_tensors.gguf"));
    const TensorInfo *t = file->find("weight");
    ASSERT_NE(t, nullptr);
    EXPECT_EQ(t->dtype, WeightDType::F32);
    EXPECT_EQ(t->shape, (std::vector<std::int64_t>{3, 2}));
    ASSERT_EQ(t->byteLength, 6u * sizeof(float));

    float values[6];
    std::memcpy(values, t->data, sizeof(values));
    EXPECT_FLOAT_EQ(values[0], 1.0f);
    EXPECT_FLOAT_EQ(values[1], 2.0f);
    EXPECT_FLOAT_EQ(values[2], 3.0f);
    EXPECT_FLOAT_EQ(values[3], 4.0f);
    EXPECT_FLOAT_EQ(values[4], 5.0f);
    EXPECT_FLOAT_EQ(values[5], 6.0f);
}

TEST(GgufReader, BiasTensorF16RawBits)
{
    auto file = loadGgufFromFile(fixturePath("test_tensors.gguf"));
    const TensorInfo *t = file->find("bias");
    ASSERT_NE(t, nullptr);
    EXPECT_EQ(t->dtype, WeightDType::F16);
    EXPECT_EQ(t->shape, (std::vector<std::int64_t>{2}));

    std::uint16_t bits[2];
    std::memcpy(bits, t->data, sizeof(bits));
    EXPECT_EQ(bits[0], 0x3800); // +0.5 in IEEE754 half precision
    EXPECT_EQ(bits[1], 0xB800); // -0.5 in IEEE754 half precision
}

TEST(GgufReader, IdsTensorI32)
{
    auto file = loadGgufFromFile(fixturePath("test_tensors.gguf"));
    const TensorInfo *t = file->find("ids");
    ASSERT_NE(t, nullptr);
    EXPECT_EQ(t->dtype, WeightDType::I32);
    EXPECT_EQ(t->shape, (std::vector<std::int64_t>{4}));

    std::int32_t values[4];
    std::memcpy(values, t->data, sizeof(values));
    EXPECT_EQ(values[0], 1);
    EXPECT_EQ(values[1], 2);
    EXPECT_EQ(values[2], 3);
    EXPECT_EQ(values[3], 4);
}

TEST(GgufReader, FindMissingTensorReturnsNull)
{
    auto file = loadGgufFromFile(fixturePath("test_tensors.gguf"));
    EXPECT_EQ(file->find("does_not_exist"), nullptr);
}

TEST(GgufReader, ReadsScalarMetadata)
{
    auto file = loadGgufFromFile(fixturePath("test_tensors.gguf"));

    // general.architecture is implicit (GGUFWriter's constructor `arch` argument).
    const GgufValue *arch = file->findMetadata("general.architecture");
    ASSERT_NE(arch, nullptr);
    EXPECT_EQ(arch->type, GgufValueType::String);
    EXPECT_EQ(arch->asString(), "campello_llm_test");

    const GgufValue *name = file->findMetadata("general.name");
    ASSERT_NE(name, nullptr);
    EXPECT_EQ(name->asString(), "campello_llm test model");

    const GgufValue *blockCount = file->findMetadata("campello_llm_test.block_count");
    ASSERT_NE(blockCount, nullptr);
    EXPECT_EQ(blockCount->type, GgufValueType::UInt32);
    EXPECT_EQ(blockCount->asUInt32(), 2u);

    const GgufValue *scale = file->findMetadata("campello_llm_test.attention.scale");
    ASSERT_NE(scale, nullptr);
    EXPECT_EQ(scale->type, GgufValueType::Float32);
    EXPECT_FLOAT_EQ(scale->asFloat32(), 0.5f);

    const GgufValue *flag = file->findMetadata("campello_llm_test.flag");
    ASSERT_NE(flag, nullptr);
    EXPECT_EQ(flag->type, GgufValueType::Bool);
    EXPECT_TRUE(flag->asBool());
}

TEST(GgufReader, ReadsStringArrayMetadata)
{
    auto file = loadGgufFromFile(fixturePath("test_tensors.gguf"));
    const GgufValue *tokens = file->findMetadata("campello_llm_test.tokens");
    ASSERT_NE(tokens, nullptr);
    EXPECT_EQ(tokens->type, GgufValueType::Array);
    EXPECT_EQ(tokens->arrayElementType, GgufValueType::String);

    const auto &array = tokens->asArray();
    ASSERT_EQ(array.size(), 3u);
    EXPECT_EQ(array[0].asString(), "<s>");
    EXPECT_EQ(array[1].asString(), "hello");
    EXPECT_EQ(array[2].asString(), "world");
}

TEST(GgufReader, FindMissingMetadataReturnsNull)
{
    auto file = loadGgufFromFile(fixturePath("test_tensors.gguf"));
    EXPECT_EQ(file->findMetadata("does.not.exist"), nullptr);
}

TEST(GgufReader, LoadFromMemoryMatchesLoadFromFile)
{
    std::string path = fixturePath("test_tensors.gguf");
    std::ifstream stream(path, std::ios::binary | std::ios::ate);
    ASSERT_TRUE(stream.is_open());
    std::streamsize size = stream.tellg();
    stream.seekg(0, std::ios::beg);
    std::vector<char> buffer(static_cast<std::size_t>(size));
    ASSERT_TRUE(stream.read(buffer.data(), size));

    auto file = loadGgufFromMemory(buffer.data(), buffer.size());
    EXPECT_EQ(file->tensors().size(), 3u);
    EXPECT_NE(file->find("weight"), nullptr);
}

TEST(GgufReader, MissingFileThrows)
{
    EXPECT_THROW(loadGgufFromFile(fixturePath("does_not_exist.gguf")), std::runtime_error);
}

TEST(GgufReader, BadMagicThrows)
{
    std::uint8_t bad[16] = {0};
    EXPECT_THROW(loadGgufFromMemory(bad, sizeof(bad)), std::runtime_error);
}

namespace
{
    template <typename T>
    void appendLE(std::vector<std::uint8_t> &buf, T value)
    {
        std::uint8_t bytes[sizeof(T)];
        std::memcpy(bytes, &value, sizeof(T));
        buf.insert(buf.end(), bytes, bytes + sizeof(T));
    }

    void appendGgufString(std::vector<std::uint8_t> &buf, const std::string &s)
    {
        appendLE<std::uint64_t>(buf, s.size());
        buf.insert(buf.end(), s.begin(), s.end());
    }
} // namespace

// A hand-built single-tensor gguf file (no metadata) whose tensor type is Q4_0 —
// a real block-quantized GGMLQuantizationType (verified against the real `gguf`
// Python package's constants.py) that campello_llm has no dequantization path for
// yet. Must throw rather than guess a layout for it.
TEST(GgufReader, UnsupportedQuantizedTensorTypeThrows)
{
    std::vector<std::uint8_t> buf;
    appendLE<std::uint32_t>(buf, 0x46554747); // magic "GGUF"
    appendLE<std::uint32_t>(buf, 3);          // version
    appendLE<std::uint64_t>(buf, 1);          // tensor_count
    appendLE<std::uint64_t>(buf, 0);          // kv_count

    appendGgufString(buf, "q");
    appendLE<std::uint32_t>(buf, 1);  // n_dims
    appendLE<std::uint64_t>(buf, 32); // dims[0]
    appendLE<std::uint32_t>(buf, 2);  // dtype = Q4_0
    appendLE<std::uint64_t>(buf, 0);  // relative offset

    buf.resize(buf.size() + 64, 0); // padding past the (unreached) data section

    EXPECT_THROW(loadGgufFromMemory(buf.data(), buf.size()), std::runtime_error);
}
