#include <gtest/gtest.h>

#include <cstdint>
#include <cstring>
#include <fstream>
#include <string>
#include <vector>

#include <campello_llm/safetensors_reader.hpp>

using namespace systems::leal::campello_llm;

namespace
{
    std::string fixturePath(const std::string &name)
    {
        return std::string(CAMPELLO_LLM_TEST_FIXTURES_DIR) + "/" + name;
    }
} // namespace

// Fixture generated by tests/fixtures/generate_test_safetensors.py (real
// `safetensors` Python package) — exact expected bytes/shapes verified against
// the actual generated file before being hardcoded here.

TEST(SafetensorsReader, ReadsAllTensorsFromFile)
{
    auto file = loadSafetensorsFromFile(fixturePath("test_tensors.safetensors"));
    ASSERT_NE(file, nullptr);
    EXPECT_EQ(file->tensors().size(), 4u);
}

TEST(SafetensorsReader, WeightTensorF32)
{
    auto file = loadSafetensorsFromFile(fixturePath("test_tensors.safetensors"));
    const TensorInfo *t = file->find("weight");
    ASSERT_NE(t, nullptr);
    EXPECT_EQ(t->dtype, WeightDType::F32);
    EXPECT_EQ(t->shape, (std::vector<std::int64_t>{2, 3}));
    ASSERT_EQ(t->byteLength, 6u * sizeof(float));

    float values[6];
    std::memcpy(values, t->data, sizeof(values));
    EXPECT_FLOAT_EQ(values[0], 1.0f);
    EXPECT_FLOAT_EQ(values[1], 2.0f);
    EXPECT_FLOAT_EQ(values[2], 3.0f);
    EXPECT_FLOAT_EQ(values[3], 4.0f);
    EXPECT_FLOAT_EQ(values[4], 5.0f);
    EXPECT_FLOAT_EQ(values[5], 6.0f);
}

TEST(SafetensorsReader, BiasTensorF16RawBits)
{
    auto file = loadSafetensorsFromFile(fixturePath("test_tensors.safetensors"));
    const TensorInfo *t = file->find("bias");
    ASSERT_NE(t, nullptr);
    EXPECT_EQ(t->dtype, WeightDType::F16);
    EXPECT_EQ(t->shape, (std::vector<std::int64_t>{2}));
    ASSERT_EQ(t->byteLength, 2u * sizeof(std::uint16_t));

    std::uint16_t bits[2];
    std::memcpy(bits, t->data, sizeof(bits));
    EXPECT_EQ(bits[0], 0x3800); // +0.5 in IEEE754 half precision
    EXPECT_EQ(bits[1], 0xB800); // -0.5 in IEEE754 half precision
}

TEST(SafetensorsReader, IdsTensorI32)
{
    auto file = loadSafetensorsFromFile(fixturePath("test_tensors.safetensors"));
    const TensorInfo *t = file->find("ids");
    ASSERT_NE(t, nullptr);
    EXPECT_EQ(t->dtype, WeightDType::I32);
    EXPECT_EQ(t->shape, (std::vector<std::int64_t>{4}));

    std::int32_t values[4];
    std::memcpy(values, t->data, sizeof(values));
    EXPECT_EQ(values[0], 1);
    EXPECT_EQ(values[1], 2);
    EXPECT_EQ(values[2], 3);
    EXPECT_EQ(values[3], 4);
}

TEST(SafetensorsReader, FlagsTensorU8)
{
    auto file = loadSafetensorsFromFile(fixturePath("test_tensors.safetensors"));
    const TensorInfo *t = file->find("flags");
    ASSERT_NE(t, nullptr);
    EXPECT_EQ(t->dtype, WeightDType::U8);
    EXPECT_EQ(t->shape, (std::vector<std::int64_t>{3}));
    ASSERT_EQ(t->byteLength, 3u);
    EXPECT_EQ(t->data[0], 1);
    EXPECT_EQ(t->data[1], 0);
    EXPECT_EQ(t->data[2], 1);
}

TEST(SafetensorsReader, ReadsMetadata)
{
    auto file = loadSafetensorsFromFile(fixturePath("test_tensors.safetensors"));
    const auto &metadata = file->metadata();
    auto it = metadata.find("format");
    ASSERT_NE(it, metadata.end());
    EXPECT_EQ(it->second, "campello_llm_test");
}

TEST(SafetensorsReader, FindMissingTensorReturnsNull)
{
    auto file = loadSafetensorsFromFile(fixturePath("test_tensors.safetensors"));
    EXPECT_EQ(file->find("does_not_exist"), nullptr);
}

TEST(SafetensorsReader, LoadFromMemoryMatchesLoadFromFile)
{
    std::string path = fixturePath("test_tensors.safetensors");
    std::ifstream stream(path, std::ios::binary | std::ios::ate);
    ASSERT_TRUE(stream.is_open());
    std::streamsize size = stream.tellg();
    stream.seekg(0, std::ios::beg);
    std::vector<char> buffer(static_cast<std::size_t>(size));
    ASSERT_TRUE(stream.read(buffer.data(), size));

    auto file = loadSafetensorsFromMemory(buffer.data(), buffer.size());
    EXPECT_EQ(file->tensors().size(), 4u);
    EXPECT_NE(file->find("weight"), nullptr);
}

TEST(SafetensorsReader, MissingFileThrows)
{
    EXPECT_THROW(loadSafetensorsFromFile(fixturePath("does_not_exist.safetensors")), std::runtime_error);
}

TEST(SafetensorsReader, TruncatedHeaderLengthThrows)
{
    std::uint8_t tooSmall[4] = {0, 0, 0, 0};
    EXPECT_THROW(loadSafetensorsFromMemory(tooSmall, sizeof(tooSmall)), std::runtime_error);
}

TEST(SafetensorsReader, UnsupportedDtypeThrows)
{
    // F8_E4M3 is a real safetensors dtype (verified against the safetensors crate's
    // Dtype enum) with no campello_llm representation yet — must throw, not guess.
    std::string jsonHeader = R"({"x":{"dtype":"F8_E4M3","shape":[1],"data_offsets":[0,1]}})";
    std::vector<std::uint8_t> buffer(8 + jsonHeader.size() + 1, 0);
    std::uint64_t headerLen = jsonHeader.size();
    std::memcpy(buffer.data(), &headerLen, sizeof(headerLen));
    std::memcpy(buffer.data() + 8, jsonHeader.data(), jsonHeader.size());

    EXPECT_THROW(loadSafetensorsFromMemory(buffer.data(), buffer.size()), std::runtime_error);
}
